version: '3.8'

services:
  app:
    build: .
    container_name: smartos_app
    command: ["npx", "tsx", "server.ts", "--host"]
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_SECRET=admin123
      - ADMIN_EMAIL=master@admin.com
      - APP_URL=http://172.17.0.2:3000
    restart: unless-stopped
